run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/rusik69/aws-iam-manager
  
  golint:
    min-confidence: 0.8
  
  misspell:
    locale: US
  
  unused:
    check-exported: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - deadcode
    - structcheck
    - misspell
    - gofmt
    - goimports
    - golint
    - gocritic
    - gocyclo
    - godot
    - gosec
    - revive
  
  disable:
    - maligned
    - prealloc
    - scopelint

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    
    # Exclude known linter issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Allow complex main function
    - path: main\.go
      linters:
        - gocyclo
  
  max-issues-per-linter: 0
  max-same-issues: 0